### ISSUE TITLE
ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by Perlence** [danielkurecka/intellij-extra-actions#6]
I've noticed that this error started to occur randomly after upgrading to PyCharm 2024.2:

```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'cz.daku.intellij.extraActions.SelectInProjectAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: cz.daku.intellij.extraActions]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```

<img width="936" alt="image" src="https://github.com/user-attachments/assets/6f29043d-bfc3-449d-8942-fa034ba47324">

**Comment by danielkurecka** [comment]
Thanks for the report, it is fixed now in version 2.0.0
